browser = chrome
url = http://www.freecrm.com
username = naveenk
password = test@123
chromeDriverPath = C:\Users\Venupriya\Downloads\139.0.7258.66 chromedriver-win64\chromedriver-win64
emailaddress = venupreeya@gmail.com
